#!/usr/bin/env bash
# Regenerate database/postgres/schema/schema.sql (read-only snapshot of the current schema)
# from the local compose Postgres. Run after adding a migration.
set -euo pipefail
cd "$(dirname "$0")/../.."

# shellcheck disable=SC1091
source scripts/localenv.sh

out=database/postgres/schema/schema.sql
mkdir -p "$(dirname "$out")"
{
  echo "-- GENERATED by database/scripts/dump_schema.sh. Do not edit; change schema via migrations."
  pg_dump "$PSQL_URL" --schema-only --no-owner --no-privileges \
  | sed -e '/^-- Dumped/d' -e '/^\\restrict/d' -e '/^\\unrestrict/d'
} > "$out"
echo "wrote $out"
